"""add document ingestion status

Revision ID: 7c58e1e79732
Revises: f7a8b9c0d1e2
Create Date: 2026-06-25 22:39:01.220790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c58e1e79732'
down_revision: Union[str, Sequence[str], None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('chunks_stored', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error')
    op.drop_column('documents', 'chunks_stored')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
